name: check-linter
on: [push]
jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install pylint
        run: pip install pylint
      - name: Run pylint
        run: pylint --fail-under=10 *.py
